# Acerca de nosotros 
"cual es la mision como escuela", "Nuestra mision es formar personas íntegras con competencias profesionales que contribuyan al desarrollo sostenible de México, mediante servicios educativos, investigación, transferencia tecnológica e innovación; con calidad de clase mundial, para satisfacer expectativas y necesidades de los sectores público, privado y social. "
"cual es mision como univercidad para el 2030", "Nuestra mision es ser una Universidad consolidada que se ha constituido en un referente internacional en la formación de capital humano, estrechamente vinculada a su entorno, cuyos resultados académicos y aportación emprendedora, la caracterizan como base del desarrollo y fortalecimiento de México, en el concierto mundial. "
"cuales son los antecedentes de la univercidad", "La Universidad Politécnica Metropolitana de Hidalgo con base en el Decreto de Creación emitido por el Ejecutivo del Estado de Hidalgo, de fecha del 17 de noviembre de 2008 opera como Organismo Descentralizado de la Administración Pública del Estado de Hidalgo, con personalidad jurídica y patrimonio propio, teniendo como objeto impartir educación superior en los niveles de licenciatura, ingeniería, especialización tecnológica y otros estudios de posgrado, así como cursos de actualización en sus diversas modalidades, para preparar profesionales con una sólida formación científica, tecnológica y en valores cívicos y éticos, conscientes del contexto nacional en lo económico, político y social; Llevar a cabo investigación aplicada y desarrollo tecnológico, pertinentes para el desarrollo económico y social de la región, del Estado y de la Nación; Difundir el conocimiento de la cultura a través de la extensión universitaria y la formación a lo largo de toda la vida; Prestar servicios tecnológicos y de asesoría, que contribuyan a mejorar el desempeño de las empresas y otras organizaciones de la región y del Estado principalmente; Impartir programas de educación continua con orientación a la capacitación para el trabajo y al fomento a la cultura tecnológica de la región, en el Estado y en el País. "
"cuales son los objetivos de la univercidad", "\n-Impartir educación superior en los niveles de licenciatura, ingeniería, especialización tecnológica y otros estudios de posgrado, así como cursos de actualización en sus diversas modalidades, para preparar profesionales con una sólida formación científica, tecnológica y en valores cívicos y éticos, conscientes del contexto Nacional en lo económico, político y social. \n-Llevar a cabo investigación aplicada y desarrollo tecnológico, pertinentes para el desarrollo económico y social de la región, del Estado y de la Nación. \n-Difundir el conocimiento y la cultura a través do la extensión universitaria y la formación a lo largo de toda la vida. \n-Prestar servicios tecnológicos y de asesoría, que contribuyan a mejorar el desempeño de las empresas y otras organizaciones de la región y del Estado, principalmente. \n-Impartir programas de educación continua con orientación a la capacitación para el trabajo y al fomento de la cultura tecnológica en la región, on el Estado y en el Pais. "
#Valores
"cuales son los valores mas importantes para la univercidad", "\n- La honestidad. \n- El respeto. \n- La equidad. \n La responsabilidad. \n- La lealtad. \n- La salidaridad. \n- El compromiso. \n- La diciplina. \n- La tolerancia. \n- La integridad. \n- La humildad."
#Directorio intitucional
"¿quien es el rector de la univercidad?", "Elqrector de la Univercidad Politecnica Metropolitana de Hidalgo es el Lic. Guillermo Mejia Ángeles."
"¿quien es la coordinadora del Programa Educativo de Ingeniería en Energía y Arquitectura Bioclimática?", "Dra. Angélica Evelin Delgadillo López" 
"¿quien es el cordinador del Programa Educativo de Licenciatura en Comercio Internacional y Aduanas?", "Mtro. Cuauhtémoc Blancas Hidalgo"
"¿quien es el coordinador del Programa Educativo en Ingeniería en Aeronáutica?", "Mtro. Pablo Alejandro Arizpe Carreón"
"¿quien es el coordinador del Programa Educativo de Ingenieríacen Tecnologías de la Información e Ingeniería en Animación y Efectos Visuales?","Dr. Víctor Manuel Zamudio García"
"¿quien es el coordinadora del Programa Educativo de Ingeniería en Logística y Transporte?", "Lic. Ahsure Tatiana Flores Pérez"
"¿quien es el coordinador de Posgrado?", "Mtro. Parley Horacio Valdés Rabling?"
#Comite de etica
"¿que es el comite de etica?", "El Comité de Ética y Prevención de Conflictos de Interés de la Universidad tiene por objeto; generar una cultura de principios y valores que fortalezcan el buen comportamiento de los servidores públicos así como para fomentar la conducta ética y mejorar el servicio público a través de normas que regulen el comportamiento y la conducta de quienes laboran en la Universidad Politécnica Metropolitana de Hidalgo."
#Maestrias
    #maestria en comercio y logistica internacional
"¿cual es el objetivo de la Maestria en Comercio y Logistica Internacional?", "Desarrollar profesionales que entiendan la complejidad de la globalización, para mejorar el intercambio comercial de México, atendiendo las necesidades de las empresas para su internacionalización, fortaleciendo la distribución de las mercancías y el cumplimiento del marco regulatorio de la materia"
"¿cual es el perfil de ingreso para la Maestria en Comercio Logistica Internacional?", "\n- Contar con una licenciatura afín al área: Logística y Transporte, Comercio Internacional y/o administrativa. \n- Demostrar experiencia profesional en actividades de tráfico, logística, despacho aduanero e importaciones y exportaciones en general. \n- Presentar examen de admisión. \n- Presentar Carta de exposición de motivos. \n- Presentar entrevista con el Comité Académico del Posgrado."
"¿cual es el perfil de egreso?", "\n-Tener una visión integral de la comercialización internacional como parte de un proceso que se lleva a cabo en la cadena de suministro y desarrollará una actitud crítica y creativa ante los problemas que se le presentan en los diversos módulos que deberá cursar. \n- Mejorar el nivel de servicio al cliente y la rentabilidad de la empresa, con el empleo de herramientas especializadas en la adecuada toma de decisiones, para la optimización de recursos y costos, impulsando la competitividad integral de la empresa en un entorno nacional e internacional.\n- Elaborar estrategias de operación y comercialización que contribuyan al posicionamiento de las organizaciones, con responsabilidad social, en mercados internacionales. \n-Interpretar la normativa aplicable a mercancías y sus medios de conducción en su ámbito nacional e internacional, para la correcta movilización y comercialización de productos. \n-Emplear sistemas de protección y resguardo de bienes conforme a la normatividad aplicable para disminuir riesgos en su manejo.\n- Gestionar el proceso integral de la cadena de suministro mediante un enfoque de valor para ofrecer productos competitivos. \n-Planear actividades de abastecimiento y distribución de mercancías, aplicando modelos de optimización para eficientar los recursos. \n-Gestionar el despacho aduanal entre la empresa, la aduana y el agente aduanal para las correctas transacciones comerciales. \n-"
"¿cual es el campo ocupacional de la Maestria en Comercio y Logistica  Internacional?", "El campo laboral de los egresados de la maestría en comercio y logística internacional es amplio, puede ser tanto en sectores públicos como privados, algunas de las opciones son: en Agencias Aduanales como Desarrolladores de Negocios, Analistas de importación y/o exportación de productos, Coordinador Logístico para trazar rutas Nacionales e Internacionales."
"¿cual es el plan de estudios?", "El Plan de Estudios de la Maestría en Comercio y Logística Internacional busca capacitar a los estudiantes para innovar y ajustar bienes y servicios a través de estudios de mercado y estrategias de marketing, basándose en las preferencias del consumidor para consolidarse en el mercado. También se enseña cómo interpretar y cumplir con las normativas aduaneras y gestionar la calidad y uso de los recursos logísticos en la cadena de suministro."
    #Maestria en ingenieria aeroespacial
"¿cual es el obejetivo de la maestria en ingenieria aeroespacial?", "La Maestría en Ingeniería Aeroespacial (MIA), tiene como objetivo general el especializar eficientemente a profesionistas en el ámbito académico e industrial nacional e internacional en materia aeroespacial, a fin del cumplimiento de dicho objetivo la especialización consta de dos áreas fundamentales también llamadas como Líneas de Generación y Aplicación del Conocimiento (LGAC)"
"¿que conforma el conocimiento (LGAC)?", "\n-PROPULSIÓN Y FLUIDOS (P&F). \n-ESTRUCTURAS, MANUFACTURA Y MATERIALES (EMM). \n-INTELIGENCIA ARTIFICIAL PARA EL CONTROL DE SISTEMAS (IACS)"
"¿cual es el objetivo general del programa de posgrado?", "\n-Generar y aplicar conocimiento en investigación y desarrollo tecnológico que contribuya a la ciencia y la tecnología nacional e internacional mediante la mejora de procesos industriales, desarrollo de proyectos de innovación tecnológica e investigación aplicada en las temáticas referentes a las LGAC,\n- Diseño de sistemas aeroespaciales, mecánicos y de procesos, análisis y validación de sistemas,\n-Llevar a cabo actividades para la organización del trabajo en equipo propiciando el desarrollo de los proyectos de investigación del NAB y la plantilla estudiantil, además de la vinculación y la movilidad con los sectores productivos y académicos " 
"¿cual es el campo ocupacional para la Maestria en Ingenieria Aeroespacial?", "El Maestro o Maestra en Ingeniería Aeroespcacial podrá desempeñar en: \n-Desarrollo de proyectos de innovación tecnológica. \n-Investigación aplicada a resolver problemáticas de sectores productivos. \n-Diseño de sistemas aeroespaciales mecánicos y de procesos, y análisis y validación de sistemas."
"¿Cual es el programa educativo de Maestria en Ingenieria Aeroespacial?", "El programa de posgrado Maestría en Ingeniería Aeroespacial (MIA) es una iniciativa de la Universidad Politécnica Metropolitana de Hidalgo, que busca formar maestrantes con valores sólidos y ética profesional para contribuir al desarrollo regional y nacional a través de proyectos que prioricen el desarrollo sustentable y la fortaleza del mercado laboral e industria aeroespacial. Los egresados de MIA deben contar con el conocimiento y habilidades necesarias para realizar proyectos relevantes para la industria y el país, identificando necesidades y áreas de oportunidad para solucionar problemáticas sociales, económicas, políticas, tecnológicas, entre otras."
    #Maestria en Inteligencia Artificial
"¿cual es el objetivo de la Maestria en Inteligencia Artificial?", "Formar profesionales en la implementación de técnicas, métodos y algoritmos de inteligencia artificial orientados la optimización y automatización de procesos aplicados tanto a la ingeniería, como al análisis de datos e inteligencia de negocios."
"¿cual es el perfil de ingreso para la Maestria en Inteligencia Artificial?", "El aspirante a la Maestría en Inteligencia Artificial deberá cumplir los siguientes requisitos: \n-Bases sólidas en el área de físico matemáticas. \n-Gusto por la ciencia y tecnología. \n-Tener espíritu emprendedor y capacidad de liderazgo. \n-Habilidad para realización de proyectos científicos y tecnológicos. \n-Capacidad de trabajar eficientemente en equipo y buena comunicación interpersonal. \n-Gusto por la programación"
"¿cual es el prefil de egreso de la maestria en inteligencia artificial?", "El egresado de este Programa Educativo será capaz de: Poseer una alta capacidad de análisis, síntesis y evaluación, además de las competencias requeridas para generar y desarrollar proyectos de innovación tecnológica en el ámbito educativo, de investigación productivo y de servicios en los sectores de automatización de procesos, inteligencia de negocios, sistemas autónomos y sensores. \nComunicarse de forma efectiva en entornos reales y virtuales; con personas provenientes de diversos orígenes y campos de estudio. \n-Analizar, comprender y desarrollar procesos de negocios competitivos para el entorno de la industria de la tecnológica. \n-Liderar equipos de trabajo multidisciplinarios. \n-Desarrollar soluciones tecnológicas que otorguen un valor agregado y ventaja competitiva a los bienes y servicios, provenientes de la empresa donde laboré. \n-Capacidad de trabajar eficientemente en equipo y buena comunicación interpersonal. \n-Aplicar los procesos de automatización a la industria donde laboré. \n-Automatizar procesos de negocio para la solución efectiva de problemas de la industria."
"¿cual es el mapa curricular?", "Cuatrimestre 1: \n-Estadistica Aplicada. \n-Automatas y Lenguaje Natural. \n-Análisis de algoritmos. Cuatrimestre 2: \n-Modelos gráficos probabilisticos. \n-Inteligencia de Negocios. \n-Web Semántica. Cuatrimestre 3: \n-Matemáticas Avanzadas. \n-Ciberseguridad. \n-Seminario de Investigación. Cuatrimestre 4: \n-Cómputo de Alto desempeño. \n-Redes Neuronales. \n-Optativa. Cuatrimertre 5: \n-Seminario de Investigación II. \n-Optativa II \n-Optativa III. Cuatrimestre 6: \n-Seminario de Investigación III. \n-Desarrollo de Tesis. \n-Optativa IV."