#Ingeniería en Aeronáutica
"¿Puedes hablarme del campo laboral para aeronáutica?","El ingeniero en aeronáutica se desempeña en organizaciones tales como:\n-Compañías de Aviación comercial de carga.\n-Líneas aéreas de transporte de pasajeros.\n-Compañías dedicadas al mantenimiento de aeronaves.\n-Empresas dedicadas a la investigación diseño y construcción de aeronaves.\n-Empresas de servicios orientados a la navegación aérea.\n-Compañías relacionadas con el estudio y diseño de materiales aerodinámicos.\n-Asesoramiento técnico relacionado con material aéreo.\n-Industria energética.\n-Industria Automotriz.\n-Sector gubernamental en el ramo de la seguridad.\n-Aeropuertos de carga y de transporte de pasajeros.\n-En toda empresa en donde se utilicen aeronaves o plantas de potencia.",
"¿Que ventajas tiene el modelo educativo de Aeronáutica?","\n-Formación bilingüe\n-Estancias y estadías nacionales e internacionales\n-Titulación automática al concluir los créditos\n-Concluye tu carrera en menos de 4 años",
"Perfil de ingreso para aeronáutica","La o el aspirante al ingresar al Programa educativo de la ingeniería en aeronáutica deberá tener:\n-Bases sólidas en el área de las ciencias físico matemáticas.\n-Gusto por las aeronaves y tecnologías relacionadas.\n-Habilidad para aprender diferentes idiomas.\n-Espíritu emprendedor y creativo.\n-Facilidad para el trabajo colaborativo.\n-Habilidades de comunicación\n-Buenos hábitos de estudio, disciplina, constancia, responsabilidad y autogestión\n-Disponibilidad de tiempo completo",
"Plan de estudos de aeronáutica","Primer cuatrimestre\n-Inglés I\n-Valores del Ser\n-Algebra Lineal\n-Cálculo Diferencial\n-Fisica Clasica\n-Lógica de Programación\n-Temas Selectos de Química\n\n-Segundo cuatrimestre\n-Inglés II\n-Inteligencia Emocional\n-Medición e Instrumentación\n-Cálculo Integral\n-Estática\n-Dibujo Asistido por Computadora\n-Probabilidad y Estadística\n\n-Tercer cuatrimestre\n-Inglés III\n-Desarrollo Interpersonal\n-Electricidad y Magnetismo\n-Ecuaciones Diferenciales\n-Dinámica\n-Termodinámica y Transferencia de Calor\n-Análisis Vectorial\n\n-Cuarto cuatrimestre\n-Inglés IV\n-Habilidades del Pensamiento\n-Mecánica de Materiales\n-Mecánica de Fluidos\n-Matemáticas Superiores con Métodos Numéricos\n-Circuitos Eléctricos\n-Estancia\n\n-Quinto cuatrimestre\n-Inglés V\n-Habilidades Organizacionales\n-Resistencia materiales\n-Aerodinámica\n-Regulaciones Aeronáuticas\n-Dispositivos Electrónicos\n-Ingenieria de Materiales\n\n•Sexto cuatrimestre\n-Inglés VI\n-Ética Profesional\n-Análisis Matricial de Estructuras\n-Mecanica de Vuelo de Ala Fija\n-Motores de Combustión Interna\n-Sistema Electrico/Electrónico de Aeronaves\n-Procesos de Fabricación\n\n-Septimo cuatrimestre\n-Inglés VII\n-Sistemas de Calidad\n-Ingeniería Asistida por Computadora\n-Diseño de elementos del Motor Alternativo\n-Dispositivos Electrónicos Programables\n-Estancia I\n-Mecanica de Vuelo de Ala Rotativa (Optativa)\n\n-Octavo cuatrimestre\n-Inglés VIII\n-Procesos Productivos\n-Diseño Aerodinámico\n-Propulsión de Aeronaves\n-Sistemas de Aeronaves\n-Manufactura Asistida por Computadora\n-Mecanica de Materiales Compuestos (Optativa)\n-\n-Noveno cuatrimestre\n-Inglés IX\n-Diseño de Elementos de Aeronaves\n-Navegación Aérea\n-Diseño de Motores\n-Formulación y Evaluación de Proyectos\n-Ingenieria de Mantenimiento Aeronautico\n-Diseño y Construccion de Aeronaves (Optativa)\n-\n-Decimo cuatrimestre\n-Estadía 600 Horas",
"Líneas de Investigación de Aeronáitica","\n-Ingeniería de materiales para la industria aeroespacial.\n-Ingeniería de propulsión."
"Líneas de Investigación:","Aplicaciones de la Inteligencia Artificial en Transporte, Medio Ambiente, Seguridad e Instrumentación Metrológica."

#Ingeniería en Animación y Efectos Visuales
"Campo ocupacional de Ingeniería en Animación y Efectos Visuales","El ingeniero en Animación y efectos visuales de la UPMH, puede trabajar en:\n-Diseñar modelos físicos de dos y tres dimensiones utilizando las técnicas artísticas del dibujo y modelado para la representación física de escenarios y personajes reales\n-Crear modelos digitales en dos y tres dimensiones utilizando las técnicas digitales para la representación virtual de escenarios y personajes reales.\n-Diseñar efectos visuales utilizando técnicas ópticas, manejo de cámaras y programas de cómputo, para darle realismo a la historia.\n-Construir efectos visuales utilizando software especializado para su postproducción.\n-Diseñar escena mediante técnicas de postproducción para la integración de los elementos multimedia y la historia.\n-Proponer estudio de mercado mediante la metodología de gestión de proyectos para asegurar la viabilidad del proyecto.\n-Implementar proyecto de animación para el logro de las metas planteadas en el proyecto en tiempo y forma mediante un plan de trabajo.\n-Por otra parte, a través de sus materias extracurriculares relacionadas, los estudiantes conocen temas para el análisis, diseño e implementación de videojuegos.",
"Ventajas del modelo educativo de Animación y Efectos Visuales","Formación bilingüe\n-Titulación automática al concluir los créditos\n-Concluye tu carrera en menos de 4 años\n-Estancias y estadías nacionales e internacionales",
"Perfil de ingreso para la Ingeniería en Animación y Efectos Visuales","La o el aspirante a ingresar al Programa Educativo de Ingeniería en Animación y Efectos Visuales deberá tener:\n-Orientación hacia el área de las ciencias físico - matemáticas.\n-Habilidades en el manejo de las tecnologías de la informática.\n-Interés por el desarrollo y la innovación tecnológica.\n-Espíritu emprendedor y creativo.\n-Gusto por la animación y la postproducción.\n-Habilidad de comunicación y tabajo en equipo.\n-Disponibilidad de tiempo completo.",
"Plan de estudios de Ingeniería en Animación y Efectos Visuales","•Primer cuatrimestre\n-Inglés I\n-Valores del Ser\n-Historia del Arte y la Animación\n-Anatomía Humana y Anima\n-Narrativa\n-Regional 1\n-Algebra Linea \n•Segundo cuatrimestre\n-Inglés II\n-Inteligencia Emocional\n-Dibujo Digital\n-Dibujo Artístico y Técnicas de Representación\n-Guionismo\n-Teoría del Color\n-Cálculo Diferencial e Integral \nTercer cuatrimestre\n-Inglés III\n-Desarrollo Interpersonal\n-Fundamentos de la Animación\n-Semiótica y Creación de Personajes\n-Taller de Modelado\n-Storyboard\n-Fundamentos de Fisica \nCuarto cuatrimestre\n-Inglés IV\n-Habilidades del Pensamiento\n-Animación 2D\n-Introducción al Modelado 3D\n-Fundamentos de Fotografía\n-Probabilidad y Estadistica\n-Estancia I\nQuinto cuatrimestre\n-Inglés V\n-Habilidades Organizacionales\n-Caracterización de Personajes 3D\n-Diseño de Escenarios en Maqueta\n-Edición y Composición Fotográfica\n-Introducción a la Animación 3D\n-Grabación de Audio\n•Sexto cuatrimestre\n-Inglés VI\n-Ética Profesional\n-Dirección Artística\n-Técnicas De Cine\n-Rigging\n-Regional 2\n-Diseño de Audio\nSeptimo cuatrimestre\n-Inglés VII\n-Cinematografía\n-Animación de Personajes en 3D\n-Mercadotecnia\n-Fundamentos y Producción de Efectos Visuales\n-Regional 3\n-Estancia II\nOctavo cuatrimestre\n-Inglés VII\n-Rigging Avanzado\n-Gestión de Proyectos\n-Dinámicos y Fluidos\n-Composicion de Efectos\n-Painting 3D\n-Regional 4\nNoveno cuatrimestre\n-Inglés IX\n-Animación 3D Avanzada\n-Emprendedor\n-Dinámicos de Cabello y Telas\n-Rendering\n-Propiedad Intelectual\n-Regional 5\nDecimo cuatrimestre\n-Estadía 600 Horas",
"Desarrollo de Videojuegos y Sistemas Interactivos.","\n-Líneas de Investigación:,\n-Análisis y desarrollo de animación y postproducción digitales para el arte audiovisual.",



#Ingeniería en Energía
"Campo ocupacional de la ingeneria en energía","La o el ingeniero en energía se desempeña en organizaciones tales como:\n-Empresas de energías renovables y alternas creadas por las y los estudiantes.\n-Empresas orientadas a la generación de electricidad y gas.\n-Industria manufacturera, extractiva, metálica básica y de maquinaria y equipo.\n-Industria eléctrica y electrónica\n-Industria alimenticia, bebidas, química y biotecnología.\n-Industria de la construcción y arquitectura bioclimática.\n-Organizaciones dedicadas al comercio, restaurantes y hoteles.\n-Instituciones de educación e investigación.\n-Empresas que generan, transportan y distribuyen energía eléctrica y combustible.\n-Organismos gubernamentales y privados de regulación energética y ecológica.\n-Agencias internacionales de promoción del uso de las energías renovables y alternas.\n-Dependencias federales, estatales y municipales.",
"Visitas industriales para inegenería en energía","La o el ingeniero en energía se desempeña en organizaciones tales como:\n-Al cursar su carrera, la o el estudiante del Programa Educativo de Ingeniería en Energía, tendrá la oportunidad de realizar visitas a instalaciones energéticas, industrias y centros de investigación, tales como:\n-Primer cuatrimestre: Parque Ecológico de Cubitos.\n-Segundo cuatrimestre: Mitutoyo Mexicana S. A. de C.V.\n-Tercer cuatrimestre: Bombardier Transportation.\n-Quinto cuatrimestre: WEG México, S.A. de C.V., Condumex S.A. de C.V.\n-Sexto cuatrimestre: Instituto Nacional de Investigaciones Nucleares.\n-Octavo cuatrimestre: Parque Eólico PIER (Iberdrola) y Agroparque La Esperanza.\n-Noveno cuatrimestre: Museo de Sitio Xochicalco-INAH.\n-Además de participar en convocatorias, congresos y expos, tales como: The Green Expo; Cleantech Challenge México; Semana Nacional de Energía Solar; Encuentro Estatal de Jóvenes Investigadores, Academia Journals, entre otras.",
"Ventajas del Modelo Educativo de ingeneria en energá","\n-Formación bilingüe\n-Estancias y estadías nacionales e internacionales\n-Titulación automática al concluir los créditos\n-Concluye tu carrera en menos de 4 años",
"Perfil de Ingreso para la ingeneria en energía","La o el aspirante a ingresar al Programa Educativo de Ingeniería en Energía deberá::\n-Contar con educación media superior concluida.\n-Tener interés por la preservación del medio ambiente, el desarrollo sostenible, y el aprovechamiento y aplicación de las energías renovables y alternas.\n-Disponibilidad de tiempo completo.\n-Deseo de realizar movilidad internacional.\n-Interés por participar en visitas industriales.\n-Convicción para trabajar por el bien común y alcanzar el éxito.\n-Visión para cosechar logros a través del aprendizaje y su aplicación en proyectos de las áreas de: eficiencia energética, sistemas solares térmicos y fotovoltaicos, sistemas de cogeneración, producción de biocombustibles, energía nuclear, sistemas hidráulicos, energía eólica, producción de hidrógeno y celdas de combustible y gestión de proyectos energéticos.\n-Interés para la obtención de certificaciones en: eficiencia energética, sistemas solares térmicos y sistemas solares fotovoltaicos.",
"Plan de estudios de ingeneria en energia","\n•Primer cuatrimestre\n-Inglés I\n-Valores del Ser\n-Cálculo Diferencial\n-Álgebra Lineal\n-Química con Laboratorio\n-Introducción a la Ingeniería en Energía\n-Programación\n-Actividades Culturales y Deportivas I\n•Segundo cuatrimestre\n\n-Inglés II\n-Inteligencia Emocional\n-Cálculo Integral\n-Termodinámica\n-Transferencia de Calor y Masa\n-Taller de Química Aplicada\n-Física con Laboratorio\n-Dibujo para Ingeniería\n-Actividades Culturales y Deportivas II\n•Tercer cuatrimestre\n-Inglés III\n-Desarrollo Interpersonal\n-Cálculo de Varias Variables\n-Ingeniería en Energía Fototérmica\n-Mecánica de Fluídos con Laboratorio\n-Taller de Química Orgánica\n-Electricidad y Magnetismo\n-Ingeniería en Tecnología Eólica\n-Riesgos Laborales\n-Actividades Culturales y Deportivas III\n•Cuarto cuatrimestre\n-Inglés IV\n-Habilidades del Pensamiento\n-Ecuaciones Diferenciales\n-Electroquímica\n-Física Moderna\n-Óptica\n-Ingeniería Asistida por Computadora\n-Estancia I\n•Quinto cuatrimestre\n-Inglés V\n-Habilidades Organizacionales\n-Taller de EC. DIF. PAR.\n-Metrología e Instrumentación\n-Ingeniería en Energía de la Biomasa\n-Ingeniería en Energía del Hidrógeno\n-Estado Sólido\n-Máquinas Eléctricas\n-Circuitos Eléctricos\n•Sexto cuatrimestre\n\n-Inglés VI\n-Ética Profesional\n-Probabilidad y Estadística\n-Ingeniería en Tecnología Fotovoltaica\n-Biomasa con Laboratorio\n-Celdas de Combustible\n-Electrónica\n-Seguridad y Medio Ambiente\n•Septimo cuatrimestre\n-Inglés VII\n-Control Estadístico de Procesos\n-Máquinas y Plantas Térmicas\n-Diseño de Experimentos\n-Física Nuclear\n-Regional I\n-Administración y Contabilidad\n-Estancia II\n•Octavo cuatrimestre\n\n-Inglés VIII\n-Ingeniería Energética\n-Almacenamiento de Energía Solar\n-Certificación Solar Térmica\n-Ingeniería en Energía Hidráulica\n-Sustentabilidad Energética\n-Conservación Bioclimática\n-Asignatura Regional II\n-Ahorro y Uso Eficiente de Energía\n•Noveno cuatrimestre\n\n-Inglés IXNormativida\n-Normatividad Y Regulación Energética\n-Certificación Eficiencia Energética (ISO 50001)\n-Tecnología de Cogeneración\n-Introducción a la Arquitectura Bioclimática\n-Asignatura Regional III\n-Automatización Industrial\n-Innovación y Gestión de Proyectos\n•Decimo cuatrimestre\n\n-Estadía 600 Horas"




#Ingeniería en Logística y Transporte
"¿cuales son las areas funcionales de la organización donde se desarrollará el egresado de ingeniería en logística y transporte?","\n-Abastecimiento\n-Producción e inventarios\n-Distribución y transporte\n-Evaluación de proyectos",
"¿cual es el campo ocupacional para ingeniería en logística y Transporte","El Ingeniero en Logística y Transporte podrá laborar en cualquier empresa de transporte de carga, manufacturera, comercial o de servicio realizando las siguientes actividades:\n-Administración de almacenes y centros de distribución.\n-Gestión de flotillas en los diferentes modos de transporte\n-Participación en procesos de compra-venta nacional e internacional.\n-Consultoría en servicios logísticos y de transporte.",
"¿cuales son las ventajas de nuestro modelo educativo para la ingeneria en logística y trasporte?","Formación bilingüe\n-Estancias y estadías nacionales e internacionales\n-Titulación automática al concluir los créditos\n-Concluye tu carrera en menos de 4 años",
"¿cual es el perfil de egreso para la ingeniería en logística y transporte","La o el egresado será capaz de innovar, diseñar y administrar sistemas logísticos y de transporte utilizando herramientas tecnológicas de vanguardia, contribuyendo al desarrollo sostenible de las organizaciones y a su inserción exitosa en los mercados competitivos.",
"¿cual es el plan de estudios de ingeniería en logística y transporte","•Primer cuatrimestre\n-Inglés I\n-Valores del Ser\n-Fundamentos de la cadena de suministro\n-Administración y principios de economía\n-Álgebra lineal\n-Calidad en la cadena de suministro\n-Probabilidad y estadística\n•Segundo cuatrimestre\n-Inglés II\n-Inteligencia Emocional\n-Logística del abastecimiento\n-Cálculo diferencial e integral\n-Química energética y ambiental\n-Control estadístico de la calidad\n-Lógica de programación\n•Tercer cuatrimestre\n-Inglés III\n-Desarrollo Interpersonal\n-TI aplicadas a los pronósticos en la cadena de suministro\n-TI aplicadas a la planeación y control de inventarios\n-Temas selectos de física\n-Introducción a la operación del transporte\n-Simulación de procesos logísticos\n•Cuarto cuatrimestre\n-Inglés IV\n-Habilidades del pensamiento\n-Logística de la producción\n-Métodos cuántitativos para la optimización\n-Sistemas de transportación ferroviario y carretero\n-TI's aplicadas al transporte\n-Estancia I\n•Quinto cuatrimestre\n-Inglés V\n-Habilidades organizacionales\n-Centros de distribución y almacenes\n-Investigación de operaciones logísticas\n-Sistemas de transportación áereo y marítimo\n-Técnicas de selección y renovación vehicular\n-Mercadotecnia\n•Sexto cuatrimestre\n-Inglés VI\n-Ética profesional\n-Planeación estratégica\n-Economía del transporte\n-Administración del mantenimiento\n-Transporte y sistemas de distribución\n-Administración del personal\n•Septimo cuatrimestre\n-Inglés VII\n-Comercio Internacional\n-Sistemas de costeo en operaciones logísticas\n-Ingeniería de transito\n-Logística y transporte sustentables\n-Metodología de la investigación\n-Estancia II\n•Octavo cuatrimestre\n-Inglés VIII\n-Logística, tráfico y aduanas\n-Operación de flotas y terminales\n-Ingeniería económica\n-Legislación y derecho del transporte\n-Estudios de ingeniería del transporte\n-Operación de almacenes de refacciones•Noveno cuatrimestre\n-Inglés IX\n-Distribución física internacional\n-Gestión y dirección de empresas\n-Formulación y evaluación de proyectos\n-Modelos de transporte y logística\n-Transporte urbano\n-Seminario de análisis de caos y decisiones\n•Decimo cuatrimestre\n-Estadía 600 Horas",



#Ingeniería en Tecnologías de la Información
"campo ocupacional para la ingeniería en tecnologías de la información ","El Ingeniero en Tecnologías de la Información de la UPMH, puede trabajar en áreas donde se requiere diseñar, construir e implementar servicios en áreas de Redes e internet, Programación de computadoras, dispositivos Móviles y Telecomunicaciones.\nPor otra parte, a través de sus materias extracurriculares relacionadas con la industria 4.0, los estudiantes conocen temas de ciencia de datos, inteligencia artificial, sistemas embebidos, metodologías ágiles, robótica e internet de las cosas.\nPuede trabajar en desarrollar soluciones innovadoras de integración de tecnologías de la información mediante metodologías de desarrollo de software, diseño de base de datos, seguridad de la información y administración de proyectos; con base en los estándares aplicables para atender las áreas de oportunidad, resolver las necesidades y optimizar los procesos y recursos de la organización, así como temas de la Industria 4.0",
"en infrestructura con que cuenta la ingeneria en tecnologias de la informacion","Infraestructura:\n-Laboratorio de Redes y Desarrollo tecnológico e Investigación\n-Laboratorio de Desarrollo de aplicaciones Móviles.\n-Laboratorio de Internet de la Cosas\n-Laboratorio de Ciencia de Datos.\n-Aulas con pantalla y mesas de trabajo.",
"¿que diferencía a la ingeneria en tecnologias de la informacion?","\n-Laboratorio de INDUSTRIA 4.0\n-Miembro del programa Microsoft IT\n-Academy como solución de capacitación y certificación de Microsoft para instituciones educativas a nivel mundial.\n-Miembro del programa CISCO Academy, para instituciones educativas a nivel mundial.\n-Miembro del programa EMC Academy, para instituciones educativas a nivel mundial.\n-Centro Certificador Grow\n-Proyectos de Investigación",
"perfil de ingreso para ingeneria en tecnologias de la informacion","\n-Orientación hacia el área de las ciencias físico-matemáticas.\n-Gusto por el desarrollo de sistemas y la innovación tecnológica.\n-Capacidad de análisis y síntesis\n-Habilidades para el razonamiento lógico y solución de problemas.\n-Espíritu creativo, emprendedor y colaborativo.\n-Enfocado a las necesidades de áreas como Internet de las Cosas, Blockchain, Cloud, Inteligencia Artificial, Realidad Virtual y Aumentada, Robótica y Ciencia de Datos.",