lista = [
    "¿Que es la transparencia?","La transparencia política es una cualidad de la actividad pública que consiste en la apertura del sector público a la divulgación de información acerca de su gestión. Una de las características de un Estado democrático es la obligación de todos los poderes públicos. Los cuidadanos de la republica tienen libre acceso a la información",
    # ----- LICENCIATURAS ------////
    # -> PERFILES DE INGRESO Y CAMPOS
    # - ->administracion empresarial
    "¿Cual es el perfil de ingreso a la licenciatura en administración y gestión empresarial?", "El perfil de esta licenciatura para ingreso debe de ser:\n -Orientación a las áreas económico administrativas.\n -Contar con habilidades matemáticas y razonamiento lógico para la toma de decisiones.\n -Disposición al trabajo colaborativo y gestionar equipos multidisciplinarios y multiculturales.\n -Espíritu emprendedor y creativo.\n -Capacidad de Liderazgo.\n -Buscar soluciones innovadoras e imaginativas.\n -Capacidad de análisis, síntesis y de evaluación de la información.\n -Comportamiento ético y profesional.",
    "¿Cual es el plan de estudios de la licenciatura en administración y gestión empresarial?", "El plan de estudios de la carrera esta basada en conocimientos generales de la misma, con ingles y materias de matematicas incluidas.\nDe primero a noveno cuatrimestre. ¿Desea conocer el plan de alguno de estos? Escriba de que cuatrimestre desea obtener mas informacion",
    "Plan de estudios de primer cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés I\nDesarrollo Humano y Valores\nIntroducción a las Matemáticas\nIntroducción a la Administración\nIntroducción a la Contabilidad\nMarco Legal de las Organizaciones\nExpresión Oral y Escrita I",
    "Plan de estudios de segundo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés II\nInteligencia Emocional y Manejo de Conflictos\nMatematicas Aplicadas a la Administración\nProceso Administrativo\nContabilidad\nDerecho Mercantil\nSistemas de Información en las Organizaciones",
    "Plan de estudios de tercer cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés III\nHabilidades Cognitivas y Creatividad\nProbabilidad y Estadística\nPlaneación Estratégica en las Organizaciones\nContabilidad Administrativa\nEconomía de la Empresa\nMetodología de la Investigación",
    "Plan de estudios de cuarto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés IV\nÉtica Profesional\nAdministración y Gestión del Talento Humano\nContabilidad de Costos - Productos\nFundamentos de Mercadotécnia\nAgregados Económicos\nEstancia I",
    "Plan de estudios de quinto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés V\nHabilidades Gerenciales\nMatematicas Financieras\nComportamiento y Desarrollo Empresarial\nContabilidad de Costos - Servicios\nInvestigación de Mercados\nLegislación Laboral",
    "Plan de estudios de sexto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VI\nLiderazgo de Equipos de Alto Desempeño\nEconometría\nAdministración Financiera\nAdministración de Sueldos y Salarios\nMercadotecnia Estratégica\nAdministración de la Calidad",
    "Plan de estudios de septimo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VII\nComercio Internacional\nSustentabilidad\nContribuciones Fiscales\nAdministración de la Producción\nTecnologías de la Información Aplicada a los Negocios\nEstancia II",
    "Plan de estudios de octavo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VIII\nNegociación y Toma de Decisiones Empresariales\nEmprendimiento\nAuditoría Administrativa\nFormulación de Proyectos\nLogística Administrativa\nResponsabilidad Social Empresarial",
    "Plan de estudios de noveno cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés IX\nAdministración de Redes Empresariales\nConsultoria\nGestión de Marca\nGestión y Evaluación de Proyectos\nExpresión Oral y Escrita II\nComercialización Internacional",
    "Plan de estudios de decimo cuatrimestre de la licenciatura en administración y gestión empresarial", "Estadía 600 Horas",
    # - ->Arquitectura bioclimatica
    "¿que es la arquitectura bioclimatica?", "Area del Estudio y construcción de edificaciones tomando en cuenta las condiciones climaticas y usar estas en favor de la infrastructura.",
    "campo ocupacional de la arquitectura bioclimatica", "-Instituciones públicas y privadas\n-Empresas u organizaciones relacionadas con el medio ambiente\n-Despachos de arquitectura con y sin especialidad en bioclimática\n-Constructoras\n-Investigación académica\n-Investigación aplicada\n-Instituciones educativas",
    # - -> perfil de ingreso (arquitectura bioclimatica)
    "¿cual es el perfil de ingreso de arquitectura bioclimatica?", "-Haber concluido su formación media superior.\n-Contar, preferentemente, con conocimientos en: matemáticas básica (aritmética, álgebra, trigonometría y geometría), física, historia, geografía, dibujo técnico y metodología de la investigación.\n-Interesarse por las artes, la historia y el diseño.\n-Tener habilidad y gusto por el dibujo y la lectura.\n-Tener habilidad para aprender otros idiomas.\n-Poseer habilidades desarrolladas de comunicación, oral, escrita y gráfica.\n-Poseer destreza para trabajar con técnicas manuales.\n-Poseer espíritu creativo, inventivo, emprendedor y colaborativo.\n-Contar con buenos hábitos de estudio, disciplina, constancia, responsabilidad y autogestión.\n-Ser observador y perceptivo de su entorno.\n-Tener interés por el cuidado y preservación del medio ambiente.\n-Tener disponibilidad de tiempo completo."
    # -> CUERPOS ACADEMICOS
    "¿Quienes son los miembros academicos de la licenciatura en administración y gestión empresarial?", "-Delgadillo Badillo Edith\n-Durán Rocha Marian\n-Fosado Martínez Dulce Olivia (responsable del Cuerpo Académico\n-Márquez Ortíz Juan Carlos",
    "¿cual es la linea de investigacion de la licenciatura en administracion y gestion empresarial?", "Fortalecimiento y consolidación de PyMES.",
    "¿que son las PyMES?", "Pyme significa pequeña y mediana empresa. Lo que caracteriza a una empresa como pyme varía entre países y regiones, pero sus características distintivas son ciertos límites de capital humano y financieros. En algunos países las empresas se clasifican según las ventas anuales y su rubro, mientras que en otros la definición está ligada con el número de empleados. Una empresa es considerada pyme cuando tiene entre 1 y 250 empleados. Tradicionalmente, las pymes se clasifican según su tamaño en pequeñas, medianas y grandes. Con el tiempo se les han sumado las microempresas, que también se incluyen al referirse a las pymes, o de forma más precisa, mipymes. Todas ellas son organizaciones con fines de lucro y sus operaciones son de menor escala que las industrias.\n(Oyster 2022, 16 de Mayo)",

]