lista = [
    # TRANSPARENCIA POLITICA
    "¿Que es la transparencia?","La transparencia política es una cualidad de la actividad pública que consiste en la apertura del sector público a la divulgación de información acerca de su gestión. Una de las características de un Estado democrático es la obligación de todos los poderes públicos. Los cuidadanos de la republica tienen libre acceso a la información",
    # ----- LICENCIATURAS ------////
    # -> PERFILES DE INGRESO Y CAMPOS
    # - ->administracion empresarial
    "¿Cual es el perfil de ingreso a la licenciatura en administración y gestión empresarial?", "El perfil de esta licenciatura para ingreso debe de ser:\n -Orientación a las áreas económico administrativas.\n -Contar con habilidades matemáticas y razonamiento lógico para la toma de decisiones.\n -Disposición al trabajo colaborativo y gestionar equipos multidisciplinarios y multiculturales.\n -Espíritu emprendedor y creativo.\n -Capacidad de Liderazgo.\n -Buscar soluciones innovadoras e imaginativas.\n -Capacidad de análisis, síntesis y de evaluación de la información.\n -Comportamiento ético y profesional.",
    "¿Cual es el plan de estudios de la licenciatura en administración y gestión empresarial?", "El plan de estudios de la carrera esta basada en conocimientos generales de la misma, con ingles y materias de matematicas incluidas.\nDe primero a noveno cuatrimestre. ¿Desea conocer el plan de alguno de estos? Escriba de que cuatrimestre desea obtener mas informacion",
    "Plan de estudios de primer cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés I\nDesarrollo Humano y Valores\nIntroducción a las Matemáticas\nIntroducción a la Administración\nIntroducción a la Contabilidad\nMarco Legal de las Organizaciones\nExpresión Oral y Escrita I",
    "Plan de estudios de segundo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés II\nInteligencia Emocional y Manejo de Conflictos\nMatematicas Aplicadas a la Administración\nProceso Administrativo\nContabilidad\nDerecho Mercantil\nSistemas de Información en las Organizaciones",
    "Plan de estudios de tercer cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés III\nHabilidades Cognitivas y Creatividad\nProbabilidad y Estadística\nPlaneación Estratégica en las Organizaciones\nContabilidad Administrativa\nEconomía de la Empresa\nMetodología de la Investigación",
    "Plan de estudios de cuarto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés IV\nÉtica Profesional\nAdministración y Gestión del Talento Humano\nContabilidad de Costos - Productos\nFundamentos de Mercadotécnia\nAgregados Económicos\nEstancia I",
    "Plan de estudios de quinto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés V\nHabilidades Gerenciales\nMatematicas Financieras\nComportamiento y Desarrollo Empresarial\nContabilidad de Costos - Servicios\nInvestigación de Mercados\nLegislación Laboral",
    "Plan de estudios de sexto cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VI\nLiderazgo de Equipos de Alto Desempeño\nEconometría\nAdministración Financiera\nAdministración de Sueldos y Salarios\nMercadotecnia Estratégica\nAdministración de la Calidad",
    "Plan de estudios de septimo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VII\nComercio Internacional\nSustentabilidad\nContribuciones Fiscales\nAdministración de la Producción\nTecnologías de la Información Aplicada a los Negocios\nEstancia II",
    "Plan de estudios de octavo cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés VIII\nNegociación y Toma de Decisiones Empresariales\nEmprendimiento\nAuditoría Administrativa\nFormulación de Proyectos\nLogística Administrativa\nResponsabilidad Social Empresarial",
    "Plan de estudios de noveno cuatrimestre de la licenciatura en administración y gestión empresarial", "Inglés IX\nAdministración de Redes Empresariales\nConsultoria\nGestión de Marca\nGestión y Evaluación de Proyectos\nExpresión Oral y Escrita II\nComercialización Internacional",
    "Plan de estudios de decimo cuatrimestre de la licenciatura en administración y gestión empresarial", "Estadía 600 Horas",
    # - ->Arquitectura bioclimatica
    "¿que es la arquitectura bioclimatica?", "Area del Estudio y construcción de edificaciones tomando en cuenta las condiciones climaticas y usar estas en favor de la infrastructura.",
    "campo ocupacional de la arquitectura bioclimatica", "-Instituciones públicas y privadas\n-Empresas u organizaciones relacionadas con el medio ambiente\n-Despachos de arquitectura con y sin especialidad en bioclimática\n-Constructoras\n-Investigación académica\n-Investigación aplicada\n-Instituciones educativas",
    "¿cual es el perfil de egreso de arquitectura bioclimatica?", "El Licenciado en Arquitectura Bioclimática, podrá desempeñarse como:\n\t-Analista de costos unitarios\n\t-Director/a y administrador/a de proyectos\n\t-Director/a ejecutivo/a\n\t-Director/a técnico/a operativo/a\n\t-Diseñador/a\n\t-Encargado/a de diseño\n\t-Encargado/a de oficina\n\t-Evaluador/a de proyectos arquitectónicos\n\t-Gerente de proyectos\n\t-Jefe/a de áreas de gestión\n\t-Proyectista\n\t-Residente de obra\n\t-Superintendente\n\t-Supervisor/a de obra\n\t-Consultor/a ambiental\n\t-Maquetador/a profesional\n\t-Investigador/a académico\n\t-Docente",
    "¿cual es el perfil de ingreso de arquitectura bioclimatica?", "-Haber concluido su formación media superior.\n-Contar, preferentemente, con conocimientos en: matemáticas básica (aritmética, álgebra, trigonometría y geometría), física, historia, geografía, dibujo técnico y metodología de la investigación.\n-Interesarse por las artes, la historia y el diseño.\n-Tener habilidad y gusto por el dibujo y la lectura.\n-Tener habilidad para aprender otros idiomas.\n-Poseer habilidades desarrolladas de comunicación, oral, escrita y gráfica.\n-Poseer destreza para trabajar con técnicas manuales.\n-Poseer espíritu creativo, inventivo, emprendedor y colaborativo.\n-Contar con buenos hábitos de estudio, disciplina, constancia, responsabilidad y autogestión.\n-Ser observador y perceptivo de su entorno.\n-Tener interés por el cuidado y preservación del medio ambiente.\n-Tener disponibilidad de tiempo completo.",
    "plan de estudios de arquitectura bioclimatica","Primer cuatrimestre:\n\t-Inglés I\n\t-Valores del Ser\n\t-Expresión Oral y Escrita I\n\t-Geometría Descriptiva\n\t-Teoría del Ambiente\n\t-Fundamentos de Diseño\n\t-Expresión Gráfica\nSegundo cuatrimestre:\n\tInglés II\n\tInteligencia Emocional\n\tCálculo\n\tAnálisis Biofuncional\n\tClimatología\n\tConceptualización Bioarquitectónica\n\tOrígenes de la Arquitectura\nTercer cuatrimestre:\n\tInglés III\n\tDesarrollo Interpersonal\n\tEcuaciones Diferenciales\n\tArquitectura Vernácula\n\tSustentabilidad y Arquitectura\n\tFormalización Bioarquitectónic\n\tEvolución de la Arquitectura\nCuarto cuatrimestre:\n\tInglés IV\n\tHabilidades del Pensamiento\n\tProcesos Constructivos\n\tDibujo Digital\n\tPsicología Ambiental\n\tHabitat Bioarquitectónico\n\tEstancia I\nQuinto cuatrimestre:\n\tInglés V\n\tHabilidades Organizacionales\n\tEstática y Resistencia de Materiales\n\tInstalaciones\n\tBiofísica\n\tMaterialidad Bioarquitectónica\n\tModernidad y Vanguardias\nSexto cuatrimestre:\n\tInglés VI\n\tÉtica Profesional\n\tAnálisis Estructural\n\tInstalaciones Bioclimáticas\n\tVentilación Pasiva\n\tDiseño Semiótico Bioarquitectónico\n\tCostos y Presupuestos\nSeptimo cuatrimestre:\n\tInglés VII\n\tAdministración de la Construcción\n\tEstructuras I\n\tTermodinámica\n\tPresentación de Proyectos\n\tDiseño Bioarquitectónico y Paisaje\n\tEstancia II\nOctavo cuatrimestre:\n\tInglés VIII\n\tAnálisis Finaciero\n\tEstructuras II\n\tTransferencia Térmica Pasiva\n\tDiseño Urbano y Territorio\n\tProyecto Bioarquitectónico Urbano\n\tConservación Bioclimática\nNoveno cuatrimestre:\n\tInglés IX\n\tGestión de Proyectos\n\tExpresión Oral y Escrita II\n\tEnergías Renovables\n\tPaisaje y Territorio\n\tProyecto Bioarquitectónico Territorial\n\tReciclaje Bioclimático\nDecimo cuatrimestre:\n\tEstadía 600 Horas",
    "","",
    # -> CUERPOS ACADEMICOS
    "¿quienes son los miembros academicos de la licenciatura en administración y gestión empresarial?", "-Delgadillo Badillo Edith\n-Durán Rocha Marian\n-Fosado Martínez Dulce Olivia (responsable del Cuerpo Académico\n-Márquez Ortíz Juan Carlos",
    "¿quienes son los miembros academicos de arquitectura bioclimatica?","-Benavides Cortes María Mayela\n-Delgadillo López Paola Marisol\n-Salazar Texco Andrés",
    "¿cual es la linea de investigacion de la licenciatura en administracion y gestion empresarial?", "Fortalecimiento y consolidación de PyMES.",
    "¿cual es la linea de investigacion de arquitectura bioclimatica?","Diseño y edificación bioclimática\n-Sostenibilidad y territorio",
    "¿que son las PyMES?", "Pyme significa pequeña y mediana empresa. Lo que caracteriza a una empresa como pyme varía entre países y regiones, pero sus características distintivas son ciertos límites de capital humano y financieros. En algunos países las empresas se clasifican según las ventas anuales y su rubro, mientras que en otros la definición está ligada con el número de empleados. Una empresa es considerada pyme cuando tiene entre 1 y 250 empleados. Tradicionalmente, las pymes se clasifican según su tamaño en pequeñas, medianas y grandes. Con el tiempo se les han sumado las microempresas, que también se incluyen al referirse a las pymes, o de forma más precisa, mipymes. Todas ellas son organizaciones con fines de lucro y sus operaciones son de menor escala que las industrias.\n(Oyster 2022, 16 de Mayo)",

]